### ISSUE TITLE
Better tokenizer

### ISSUE THREAD

**Issue by PonteIneptique** [chartes/deucalion-model-af#2]
Il faudrait avoir un meilleur tokenizer. Pour l'instant, ca s'arrêter sur les points en gros. Il faudrait que ca puisse prendre en compte `...`, `?`, etc..

Rappel de tokenizer:
```python

def simple_tokenizer(text, lower):
    section, fullstop = regexsplitter(SECTION), regexsplitter(FULLSTOP)
    word = regexsplitter(WORD)
    for line in section(text):
        for sentence in fullstop(line):
            sentence = [w for raw in sentence.split() for w in word(raw)]
            if lower:
                sentence = [w.lower() for w in sentence]
            yield sentence
```

**Comment by PonteIneptique** [comment]
Je rebumpe @Jean-Baptiste-Camps sur ce point :')
Faudrait aussi que je fasse de l'autocat...

**Comment by Jean-Baptiste-Camps** [comment]
Juste pour être sûr, on ne peut pas s'en sortir (contrairement à l'entraînement) en redéfinissant "breakline_data" dans la config ? Dommage que FULLSTOP soit en dur.

**Comment by Jean-Baptiste-Camps** [comment]
Et, pour être clair, il faudrait l'implémenter en utilisant nlp-pie-taggers, non ?

**Comment by PonteIneptique** [comment]
La config n'a pas d'influence la-dessus, pour ca qu'il faut reecrire une fonction ;)\

cf. https://github.com/cltk/cltk/blob/master/cltk/tokenize/old_french/params.py ?
